In [1]:
import sys
import os
mp = os.path.abspath(os.path.join('/content/drive/My Drive/GraduationThesis/gitrepo/GraduationThesis/'))
sys.path.append(mp)

In [2]:
import torch
from datetime import date, datetime
import numpy as np
from modules import Reconstruction, Visualization, Utils, Network

In [3]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [4]:
# Define data set name and constraint type
dataset_name = 'superior'
current_datef = '20210409'
current_dateg = date.today().strftime("%Y%m%d")
# current_date = '20210330'
attemptf = '1'
attemptg = '3'
epoch = 15000

print(datetime.now())

2021-04-11 11:56:57.204011


In [5]:
# Load points
filename = mp + '/dataset/2d/' + dataset_name + '.vert'
data = Utils.read_txt2(filename, k_distance=50, device=device)
# data = Utils.circle_dataset(device=device)

In [6]:
traineddata_path_f = mp + '/models/' + current_datef + '_' + attemptf + '_f' + '.traineddata'
traineddata_path_g = mp + '/models/' + current_dateg + '_' + attemptg + '_g' + '.traineddata'
# traineddata_path = None
modelf, optimizer, scheduler = Network.load_model_f(traineddata_path_f, dimension=2, device=device)
model, optimizer, scheduler = Network.load_model_g(traineddata_path_g, modelf, dimension=2, device=device)

Model loaded
No model found. New model created


In [7]:
outfile = mp + '/figures/loss_value/' + current_dateg + '_' + attemptg + '_g' + '.npy'
# outfile = None
model, optimizer, scheduler, loss_value = Reconstruction.train_constraint(epoch,
                                                          model,
                                                          optimizer,
                                                          scheduler,
                                                          batch_size=None,
                                                          data=data,
                                                          loss_output_path=outfile,
                                                          device=device)

Setting up
No previous loss value found.
Getting sampling range
518

Training
tensor([[0.1542],
        [1.0248],
        [2.2073]], device='cuda:0', grad_fn=<AddmmBackward>)
tensor([[0.1404],
        [1.2259],
        [2.4910]], device='cuda:0', grad_fn=<AddmmBackward>)
tensor([[0.1628],
        [1.3578],
        [2.7016]], device='cuda:0', grad_fn=<AddmmBackward>)
tensor([[0.1553],
        [1.4305],
        [2.8041]], device='cuda:0', grad_fn=<AddmmBackward>)
tensor([[0.1476],
        [1.4822],
        [2.8872]], device='cuda:0', grad_fn=<AddmmBackward>)
tensor([[0.1464],
        [1.5456],
        [2.9759]], device='cuda:0', grad_fn=<AddmmBackward>)
tensor([[0.1406],
        [1.5908],
        [3.0475]], device='cuda:0', grad_fn=<AddmmBackward>)
tensor([[0.1333],
        [1.6238],
        [3.0996]], device='cuda:0', grad_fn=<AddmmBackward>)
tensor([[0.1220],
        [1.6449],
        [3.1281]], device='cuda:0', grad_fn=<AddmmBackward>)
tensor([[0.1124],
        [1.6499],
        [3.13

KeyboardInterrupt: ignored

In [ ]:
# attempt = '17'
# current_date = date.today().strftime("%Y%m%d")
save_path = mp + '/models/' + current_date + '_' + attemptg + '_g' + '.traineddata'
Network.save_model(save_path, model, optimizer, scheduler)

In [ ]:
constraint_output_path = None
vtk_output_path = None
Visualization.visualize2(model, data, 
                         constraint_output_path=constraint_output_path, 
                         vtk_output_path=vtk_output_path,
                         scatter=True, vecfield=True, surface=True, filled_contour=True,
                         device=device)

In [ ]:
# print(modelf(data[:,0:2]).abs().mean())
# x = model(data[:,0:2]).abs().mean()
# x = torch.tensor([[0,1], [1,2], [4,5], [6,7]])
# print(x[-2:,:])